# Generated by Django 4.0.4 on 2022-06-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cli_nombre', models.CharField(max_length=64)),
                ('cli_apellido', models.CharField(max_length=64)),
                ('cli_razon_social', models.CharField(max_length=64)),
                ('cli_dni', models.CharField(max_length=64)),
                ('cli_ruc', models.CharField(max_length=64)),
                ('cli_email', models.CharField(max_length=64)),
                ('cli_contacto', models.CharField(max_length=64, null=True)),
                ('cli_telefono', models.CharField(max_length=64, null=True)),
                ('cli_departament', models.CharField(max_length=64, null=True)),
                ('cli_provincia', models.CharField(max_length=64, null=True)),
                ('cli_distrito', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
