# Generated by Django 4.0.4 on 2022-06-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0002_rename_cli_departament_clientes_cli_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cli_razon_social',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
