# Generated by Django 4.0.4 on 2022-06-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0003_alter_clientes_cli_razon_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cli_ruc',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
