# Generated by Django 4.0.4 on 2022-06-20 16:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0005_productos_servicios_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proformas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_codigo', models.CharField(max_length=64)),
                ('prof_cliente', models.CharField(max_length=64)),
                ('prof_fecha', models.DateTimeField()),
                ('prof_valor_total', models.FloatField()),
                ('prof_estado', models.CharField(max_length=64)),
                ('prof_productos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=None)),
                ('prof_cantidad', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
    ]
