# Generated by Django 4.0.4 on 2022-06-20 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0006_proformas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proformas',
            name='prof_codigo',
        ),
    ]
