# Generated by Django 4.0.4 on 2022-06-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0007_remove_proformas_prof_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformas',
            name='prof_fecha',
            field=models.CharField(max_length=64),
        ),
    ]
