# Generated by Django 4.0.4 on 2022-06-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0009_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='usr_email',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
