# Generated by Django 4.0.4 on 2022-06-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0010_alter_usuarios_usr_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cli_razon_social',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
