# Generated by Django 4.0.4 on 2022-06-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0012_productos_pro_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='pro_categoria',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='productos',
            name='pro_codigo',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='productos',
            name='pro_codigo_sunat',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='pro_moneda',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='pro_nombre',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='productos',
            name='pro_sub_categoria',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='productos',
            name='pro_unidad_med',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
