# Generated by Django 4.0.4 on 2022-06-26 18:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0014_alter_clientes_id_alter_productos_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proformas',
            name='prof_cantidad',
        ),
        migrations.AlterField(
            model_name='proformas',
            name='prof_cliente',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=None),
        ),
    ]
