# Generated by Django 4.0.4 on 2022-06-26 21:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0016_facturas_guias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformas',
            name='prof_productos',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=None), size=None),
        ),
    ]
