# Generated by Django 4.0.4 on 2022-06-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0019_proformas_prof_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='usr_celular',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='usr_tipo',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
