# Generated by Django 4.0.4 on 2022-06-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0021_perfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='pro_stock',
            field=models.IntegerField(null=True),
        ),
    ]
