# Generated by Django 4.0.4 on 2022-06-29 03:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0022_productos_pro_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='fac_descuentos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='productos',
            name='pro_stock',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
