# Generated by Django 4.0.4 on 2022-06-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0023_facturas_fac_descuentos_alter_productos_pro_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='fac_condi_pago',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
