# Generated by Django 4.0.4 on 2022-06-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0024_facturas_fac_condi_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='pro_almacen',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cli_apellido',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cli_dni',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cli_email',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cli_nombre',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
