# Generated by Django 4.0.4 on 2022-06-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0025_productos_pro_almacen_alter_clientes_cli_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='pro_descuento',
        ),
        migrations.AlterField(
            model_name='servicios',
            name='ser_categoria',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='ser_nombre',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='ser_precio_venta_con_igv',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='ser_precio_venta_sin_igv',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='ser_sub_categoria',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='ser_unidad_med',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
