# Generated by Django 4.0.4 on 2022-06-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0026_remove_productos_pro_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='pro_categoria',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='pro_codigo',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='pro_nombre',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='pro_precio_compra_con_igv',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='pro_precio_compra_sin_igv',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='pro_precio_venta_con_igv',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='pro_precio_venta_sin_igv',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='pro_sub_categoria',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
