# Generated by Django 4.0.4 on 2022-06-29 15:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0028_proformas_prof_descuentos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformas',
            name='prof_estado',
            field=models.CharField(default='NoGenerada', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='proformas',
            name='prof_productos',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=None), null=True, size=None),
        ),
    ]
