# Generated by Django 4.0.4 on 2022-06-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0029_alter_proformas_prof_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformas',
            name='prof_tipo_cambio',
            field=models.FloatField(default=0, null=True),
        ),
    ]
