# Generated by Django 4.0.4 on 2022-06-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0030_proformas_prof_tipo_cambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='guias',
            name='gui_codigo',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='guias',
            name='gui_estado',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='guias',
            name='gui_fecha',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
