# Generated by Django 4.0.4 on 2022-06-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0033_facturas_fac_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='fac_codigo',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
