# Generated by Django 4.0.4 on 2022-07-05 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0037_cli'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cli',
            new_name='clients',
        ),
    ]
