# Generated by Django 4.0.4 on 2022-07-05 23:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0038_rename_cli_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128, null=True)),
                ('codigo', models.CharField(max_length=128, null=True)),
                ('categoria', models.CharField(max_length=128, null=True)),
                ('sub_categoria', models.CharField(max_length=128, null=True)),
                ('unidad_med', models.CharField(max_length=128, null=True)),
                ('precio_compra_sin_igv', models.FloatField(default=0, null=True)),
                ('precio_compra_con_igv', models.FloatField(default=0, null=True)),
                ('precio_venta_sin_igv', models.FloatField(default=0, null=True)),
                ('precio_venta_con_igv', models.FloatField(default=0, null=True)),
                ('codigo_sunat', models.CharField(max_length=128, null=True)),
                ('moneda', models.CharField(max_length=128, null=True)),
                ('stock', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None), null=True, size=None)),
            ],
        ),
    ]
