# Generated by Django 4.0.4 on 2022-07-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0039_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=64, null=True)),
                ('categoria', models.CharField(max_length=64, null=True)),
                ('sub_categoria', models.CharField(max_length=64, null=True)),
                ('unidad_med', models.CharField(max_length=64, null=True)),
                ('precio_venta_sin_igv', models.FloatField(default=0, null=True)),
                ('precio_venta_con_igv', models.FloatField(default=0, null=True)),
            ],
        ),
    ]
