# Generated by Django 4.0.6 on 2022-07-12 21:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0040_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='cotizaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), null=True, size=None)),
                ('productos', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None), null=True, size=None)),
                ('pagoProforma', models.CharField(max_length=30, null=True)),
                ('monedaProforma', models.CharField(max_length=30, null=True)),
                ('fechaProforma', models.CharField(max_length=30, null=True)),
                ('vendedorProforma', models.CharField(max_length=30, null=True)),
                ('celularProforma', models.CharField(max_length=30, null=True)),
                ('codigoProforma', models.CharField(max_length=30, null=True)),
                ('tipoCambio', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
