# Generated by Django 4.0.6 on 2022-07-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0041_cotizaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciones',
            name='estadoProforma',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
