# Generated by Django 4.0.6 on 2022-07-13 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0042_cotizaciones_estadoproforma'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facturas',
        ),
    ]
