# Generated by Django 4.0.6 on 2022-07-13 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0043_delete_facturas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.DeleteModel(
            name='Guias',
        ),
        migrations.RemoveField(
            model_name='perfiles',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
        migrations.DeleteModel(
            name='Proformas',
        ),
        migrations.DeleteModel(
            name='Servicios',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
        migrations.DeleteModel(
            name='Perfiles',
        ),
    ]
