# Generated by Django 4.0.6 on 2022-07-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0044_delete_clientes_delete_guias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='celular',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='codigo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tipo',
            field=models.CharField(max_length=20),
        ),
    ]
