# Generated by Django 4.0.6 on 2022-07-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0045_alter_userprofile_celular_alter_userprofile_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='direccion_fiscal',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
