# Generated by Django 4.0.6 on 2022-07-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0046_clients_direccion_fiscal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ingresos_stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('producto_id', models.CharField(max_length=32)),
                ('producto_codigo', models.CharField(max_length=32)),
                ('almacen', models.CharField(max_length=32)),
                ('cantidad', models.CharField(max_length=32)),
            ],
        ),
    ]
