# Generated by Django 4.0.6 on 2022-07-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0047_ingresos_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresos_stock',
            name='almacen',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='ingresos_stock',
            name='cantidad',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='ingresos_stock',
            name='producto_codigo',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='ingresos_stock',
            name='producto_id',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
