# Generated by Django 4.0.6 on 2022-07-16 06:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0048_alter_ingresos_stock_almacen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizaciones',
            name='celularProforma',
        ),
        migrations.RemoveField(
            model_name='cotizaciones',
            name='vendedorProforma',
        ),
        migrations.AddField(
            model_name='cotizaciones',
            name='servicios',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=None), null=True, size=None),
        ),
        migrations.AddField(
            model_name='cotizaciones',
            name='tipoProforma',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='cotizaciones',
            name='vendedor',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='cotizaciones',
            name='cliente',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='cotizaciones',
            name='productos',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=None), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='cotizaciones',
            name='tipoCambio',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), null=True, size=None),
        ),
    ]
