# Generated by Django 4.0.6 on 2022-07-16 07:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0049_remove_cotizaciones_celularproforma_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='guias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), null=True, size=None)),
                ('productos', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=None), null=True, size=None)),
                ('servicios', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=None), null=True, size=None)),
                ('vendedor', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), null=True, size=None)),
                ('pagoGuia', models.CharField(max_length=30, null=True)),
                ('monedaGuia', models.CharField(max_length=30, null=True)),
                ('fechaGuia', models.CharField(max_length=30, null=True)),
                ('tipoGuia', models.CharField(max_length=32, null=True)),
                ('codigoGuia', models.CharField(max_length=30, null=True)),
                ('tipoCambio', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), null=True, size=None)),
                ('estadoGuia', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
