# Generated by Django 4.0.6 on 2022-07-17 19:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0051_facturas'),
    ]

    operations = [
        migrations.CreateModel(
            name='boletas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), null=True, size=None)),
                ('productos', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=None), null=True, size=None)),
                ('servicios', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=None), null=True, size=None)),
                ('vendedor', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), null=True, size=None)),
                ('pagoBoleta', models.CharField(max_length=30, null=True)),
                ('monedaBoleta', models.CharField(max_length=30, null=True)),
                ('fechaBoleta', models.CharField(max_length=30, null=True)),
                ('tipoBoleta', models.CharField(max_length=32, null=True)),
                ('codigoBoleta', models.CharField(max_length=30, null=True)),
                ('tipoCambio', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), null=True, size=None)),
                ('estadoBoleta', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
