# Generated by Django 4.0.6 on 2022-07-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0053_ingresos_stock_fechaingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciones',
            name='fechaVencProforma',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
