# Generated by Django 4.0.6 on 2022-07-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0054_cotizaciones_fechavencproforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='guias',
            name='codigoProfora',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
