# Generated by Django 4.0.6 on 2022-07-18 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0055_guias_codigoprofora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guias',
            old_name='codigoProfora',
            new_name='codigoProforma',
        ),
    ]
