# Generated by Django 4.0.6 on 2022-07-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0056_rename_codigoprofora_guias_codigoproforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='guias',
            name='fechaVencGuia',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
