# Generated by Django 4.0.6 on 2022-07-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0057_guias_fechavencguia'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletas',
            name='codigoGuia',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='facturas',
            name='codigoGuia',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
