# Generated by Django 4.0.6 on 2022-07-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0058_boletas_codigoguia_facturas_codigoguia'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletas',
            name='fechaVencBoleta',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='facturas',
            name='fechaVencFactura',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
