# Generated by Django 4.0.6 on 2022-07-18 20:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0060_guias_datostraslado'),
    ]

    operations = [
        migrations.AddField(
            model_name='guias',
            name='datosTransportista',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64, null=True), null=True, size=None),
        ),
    ]
