# Generated by Django 4.0.6 on 2022-07-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0061_guias_datostransportista'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciones',
            name='imprimirDescuento',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
