# Generated by Django 4.0.6 on 2022-07-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0062_cotizaciones_imprimirdescuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletas',
            name='imprimirDescuento',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='facturas',
            name='imprimirDescuento',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
