# Generated by Django 4.0.6 on 2022-07-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0063_boletas_imprimirdescuento_facturas_imprimirdescuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stockTotal',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
