# Generated by Django 4.0.6 on 2022-07-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0064_products_stocktotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='config_docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boletaSeria', models.CharField(max_length=128, null=True)),
                ('boletaNro', models.CharField(max_length=128, null=True)),
                ('facturaSerie', models.CharField(max_length=128, null=True)),
                ('facturaNro', models.CharField(max_length=128, null=True)),
                ('guiaSerie', models.CharField(max_length=128, null=True)),
                ('guiaNro', models.CharField(max_length=128, null=True)),
                ('tokenDoc', models.CharField(max_length=128, null=True)),
            ],
        ),
    ]
