# Generated by Django 4.0.6 on 2022-07-21 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0065_config_docs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config_docs',
            old_name='boletaSeria',
            new_name='boletaSerie',
        ),
    ]
