# Generated by Django 4.0.6 on 2022-07-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0067_boletas_nroboleta_boletas_serieboleta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='cuotasFactura',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='guias',
            name='ubigeoGuia',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
