# Generated by Django 4.0.6 on 2022-07-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0068_facturas_cuotasfactura_guias_ubigeoguia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='stockTotal',
            field=models.CharField(default='0', max_length=128),
        ),
    ]
