# Generated by Django 4.0.6 on 2022-07-23 18:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0069_alter_products_stocktotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresos_stock',
            name='vendedorStock',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), null=True, size=None),
        ),
    ]
