# Generated by Django 4.0.6 on 2022-07-31 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0071_guias_codigofactura_guias_idfactura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guias',
            name='codigoProforma',
        ),
    ]
