# Generated by Django 4.0.6 on 2022-08-01 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0072_remove_guias_codigoproforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciones',
            name='cantidadCuotas',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
