# Generated by Django 4.0.6 on 2022-08-01 02:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0073_cotizaciones_cantidadcuotas'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='fechasCuotas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64, null=True), null=True, size=None),
        ),
    ]
