# Generated by Django 4.0.6 on 2022-08-03 05:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0074_facturas_fechascuotas'),
    ]

    operations = [
        migrations.CreateModel(
            name='notaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), null=True, size=None)),
                ('productos', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=None), null=True, size=None)),
                ('servicios', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=None), null=True, size=None)),
                ('vendedor', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), null=True, size=None)),
                ('tipoComprobante', models.CharField(max_length=64, null=True)),
                ('serieComprobante', models.CharField(max_length=64, null=True)),
                ('nroComprobante', models.CharField(max_length=64, null=True)),
                ('fechaComprobante', models.CharField(max_length=64, null=True)),
                ('fechaEmision', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
