# Generated by Django 4.0.6 on 2022-08-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0076_notacredito_codigocomprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacredito',
            name='codigoNotaCredito',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
