# Generated by Django 4.0.6 on 2022-08-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0077_notacredito_codigonotacredito'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacredito',
            name='estadoNotaCredito',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
