# Generated by Django 4.0.6 on 2022-08-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0078_notacredito_estadonotacredito'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pesoProducto',
            field=models.CharField(default='0', max_length=128),
        ),
    ]
