# Generated by Django 4.0.6 on 2022-08-03 07:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0079_products_pesoproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='direccion_fiscal',
            field=models.CharField(default='SinDireccion', max_length=64),
        ),
        migrations.AlterField(
            model_name='clients',
            name='direcciones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=None),
        ),
    ]
