# Generated by Django 4.0.6 on 2022-08-03 08:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0080_alter_clients_direccion_fiscal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='direcciones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), null=True, size=None),
        ),
    ]
