# Generated by Django 4.0.6 on 2022-08-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0081_alter_clients_direcciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='moneda',
            field=models.CharField(default='SOLES', max_length=128),
        ),
    ]
