# Generated by Django 4.0.6 on 2022-08-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0082_alter_products_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='config_docs',
            name='notaNro',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='config_docs',
            name='notaSerie',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
