# Generated by Django 4.0.6 on 2022-08-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0083_config_docs_notanro_config_docs_notaserie'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacredito',
            name='nroNota',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='serieNota',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
