# Generated by Django 4.0.6 on 2022-08-04 02:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0085_config_docs_notafactnro_config_docs_notafactserie'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacredito',
            name='tipoCambio',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=['3.941', '3.919'], size=None),
        ),
    ]
