# Generated by Django 4.0.6 on 2022-08-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0086_notacredito_tipocambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacredito',
            name='imprimirDescuento',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='monedaNota',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='tipoItemsNota',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
