# Generated by Django 4.0.6 on 2022-08-04 15:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0087_notacredito_imprimirdescuento_notacredito_monedanota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notacredito',
            name='tipoCambio',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), null=True, size=None),
        ),
    ]
