# Generated by Django 4.0.6 on 2022-08-04 16:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0088_alter_notacredito_tipocambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='guias',
            name='datosVehiculo',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), null=True, size=None),
        ),
    ]
