# Generated by Django 4.0.6 on 2022-08-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0090_facturas_codigosguias'),
    ]

    operations = [
        migrations.AddField(
            model_name='guias',
            name='cantidadCuotas',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
