# Generated by Django 4.0.6 on 2022-08-11 10:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0091_guias_cantidadcuotas'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletas',
            name='codigosGuias',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), null=True, size=None),
        ),
    ]
