# Generated by Django 4.0.6 on 2022-08-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0092_boletas_codigosguias'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciones',
            name='observacionesCot',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
