# Generated by Django 4.0.6 on 2022-08-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0093_cotizaciones_observacionescot'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciones',
            name='nroDocumento',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
