# Generated by Django 4.0.6 on 2022-08-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0094_cotizaciones_nrodocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='guias',
            name='nroDocumento',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='guias',
            name='observacionesGuia',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
