# Generated by Django 4.0.6 on 2022-08-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0095_guias_nrodocumento_guias_observacionesguia'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletas',
            name='nroDocumento',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='facturas',
            name='nroDocumento',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
