# Generated by Django 4.0.6 on 2022-08-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0097_alter_boletas_cliente_alter_clients_direccion_fiscal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciones',
            name='imprimirPU',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='cotizaciones',
            name='imprimirVU',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='cotizaciones',
            name='nroCotizacion',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='cotizaciones',
            name='serieCotizacion',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
