# Generated by Django 4.1 on 2022-08-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0099_config_docs_cotinro_config_docs_cotiserie'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletas',
            name='estadoSunat',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='facturas',
            name='estadoSunat',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='guias',
            name='estadoSunat',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
