# Generated by Django 4.1 on 2022-08-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0100_boletas_estadosunat_facturas_estadosunat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletas',
            name='estadoSunat',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='config_docs',
            name='tokenDoc',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='estadoSunat',
            field=models.CharField(default='', max_length=128),
        ),
    ]
