# Generated by Django 4.1 on 2022-08-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0101_alter_boletas_estadosunat_alter_config_docs_tokendoc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresos_stock',
            name='producto_nombre',
            field=models.CharField(default='', max_length=256),
        ),
    ]
