# Generated by Django 4.1 on 2022-08-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0102_ingresos_stock_producto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciones',
            name='fecha_emision',
            field=models.DateField(null=True),
        ),
    ]
