# Generated by Django 4.1 on 2022-08-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0103_cotizaciones_fecha_emision'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletas',
            name='fecha_emision',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='facturas',
            name='fecha_emision',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='guias',
            name='fecha_emision',
            field=models.DateField(null=True),
        ),
    ]
