# Generated by Django 4.1 on 2022-08-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0104_boletas_fecha_emision_facturas_fecha_emision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guias',
            name='datos_generales_guia',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='guias',
            name='datos_raros_guia',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
