# Generated by Django 4.1 on 2022-08-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0106_remove_guias_datos_generales_guia'),
    ]

    operations = [
        migrations.AddField(
            model_name='guias',
            name='nuevos_datos_migrados',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
