# Generated by Django 4.1 on 2022-08-23 20:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0109_remove_guias_datos_raros_guia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None), default=[], size=None),
        ),
    ]
