# Generated by Django 4.1 on 2022-08-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0110_alter_products_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='regBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreBanco', models.CharField(max_length=256, null=True)),
                ('monedaCuenta', models.CharField(max_length=256, null=True)),
                ('nroCuenta', models.CharField(max_length=256, null=True)),
                ('saldoCuenta', models.CharField(default='0', max_length=256)),
            ],
        ),
    ]
