# Generated by Django 4.1 on 2022-08-26 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0111_regbancario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='regBancario',
            new_name='regCuenta',
        ),
    ]
