# Generated by Django 4.1 on 2022-08-26 07:13

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0112_rename_regbancario_regcuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='regOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCuentaBank', models.CharField(default='0', max_length=64)),
                ('fechaOperacion', models.DateField(default=datetime.date.today)),
                ('detalleOperacion', models.CharField(default='', max_length=256)),
                ('montoOperacion', models.CharField(default='0', max_length=256)),
                ('saldoOperacion', models.CharField(default='0', max_length=256)),
                ('lugarOperacion', models.CharField(default='0', max_length=128)),
                ('nroOperacion', models.CharField(default='0', max_length=64)),
                ('horaOperacion', models.DateField(default=datetime.date.today)),
                ('tipoOperacion', models.CharField(default='EGRESO', max_length=64)),
                ('estadoOperacion', models.CharField(default='IMCOMPLETO', max_length=128)),
                ('clienteOperacion', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=[], size=None)),
                ('comprobanteOperacion', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=[], size=None)),
                ('guiaOperacion', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=[], size=None)),
                ('vendedorOperacion', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=[], size=None)),
                ('cotizacionOperacion', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=[], size=None)),
            ],
        ),
        migrations.AlterField(
            model_name='regcuenta',
            name='monedaCuenta',
            field=models.CharField(default='SOLES', max_length=256),
        ),
        migrations.AlterField(
            model_name='regcuenta',
            name='nombreBanco',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='regcuenta',
            name='nroCuenta',
            field=models.CharField(default='', max_length=256),
        ),
    ]
