# Generated by Django 4.1 on 2022-08-26 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0113_regoperacion_alter_regcuenta_monedacuenta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regcuenta',
            old_name='nombreBanco',
            new_name='bancoCuenta',
        ),
    ]
