# Generated by Django 4.1 on 2022-08-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0114_rename_nombrebanco_regcuenta_bancocuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='regoperacion',
            name='monedaOperacion',
            field=models.CharField(default='SOLES', max_length=128),
        ),
    ]
