# Generated by Django 4.1 on 2022-08-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0115_regoperacion_monedaoperacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='regoperacion',
            name='fechaValuta',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='regoperacion',
            name='horaOperacion',
            field=models.CharField(default='', max_length=64),
        ),
    ]
