# Generated by Django 4.1 on 2022-08-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0116_regoperacion_fechavaluta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regoperacion',
            name='usuarioOperacion',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='regoperacion',
            name='utcOperacion',
            field=models.CharField(default='', max_length=128),
        ),
    ]
