# Generated by Django 4.1 on 2022-08-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0117_regoperacion_usuariooperacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regoperacion',
            name='cargoOperacion',
            field=models.CharField(default='0', max_length=128),
        ),
        migrations.AddField(
            model_name='regoperacion',
            name='itfOperacion',
            field=models.CharField(default='0', max_length=128),
        ),
    ]
