# Generated by Django 4.1 on 2022-09-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistema_2", "0118_regoperacion_cargooperacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="boletas",
            name="registroBoleta",
            field=models.CharField(default="0", max_length=64),
        ),
        migrations.AddField(
            model_name="facturas",
            name="registroFactura",
            field=models.CharField(default="0", max_length=64),
        ),
    ]
