# Generated by Django 4.1 on 2022-09-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistema_2", "0120_cotizaciones_registrocoti"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="direccion_fiscal",
            field=models.CharField(default="SinDireccion", max_length=512),
        ),
    ]
