# Generated by Django 4.1 on 2022-09-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistema_2", "0123_regoperacion_clienteexcel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="regoperacion",
            name="referencia2",
            field=models.CharField(default="", max_length=256),
        ),
    ]
