# Generated by Django 4.1.1 on 2022-09-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0124_regoperacion_referencia2'),
    ]

    operations = [
        migrations.CreateModel(
            name='abonosOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_banco', models.CharField(default='0', max_length=64)),
                ('id_cliente', models.CharField(default='0', max_length=64)),
                ('nro_operacion', models.CharField(default='0', max_length=64)),
                ('codigo_comprobante', models.CharField(default='', max_length=64)),
                ('codigo_guia', models.CharField(default='', max_length=64)),
                ('codigo_coti', models.CharField(default='', max_length=64)),
                ('codigo_vendedor', models.CharField(default='', max_length=64)),
            ],
        ),
    ]
