# Generated by Django 4.1.1 on 2022-09-21 16:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0125_abonosoperacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abonosoperacion',
            name='id_banco',
        ),
        migrations.RemoveField(
            model_name='abonosoperacion',
            name='id_cliente',
        ),
        migrations.AddField(
            model_name='abonosoperacion',
            name='banco_datos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), default=[], size=None),
        ),
        migrations.AddField(
            model_name='abonosoperacion',
            name='datos_cliente',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), default=[], size=None),
        ),
    ]
