# Generated by Django 4.1.1 on 2022-09-21 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0126_remove_abonosoperacion_id_banco_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abonosoperacion',
            old_name='banco_datos',
            new_name='datos_banco',
        ),
    ]
