# Generated by Django 4.1.1 on 2022-09-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0129_abonosoperacion_idregistroop'),
    ]

    operations = [
        migrations.AddField(
            model_name='regoperacion',
            name='conectado_abono',
            field=models.CharField(default='0', max_length=64),
        ),
    ]
