# Generated by Django 4.1.1 on 2022-10-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0131_userprofile_rolesusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='facturaPagada',
            field=models.CharField(default='0', max_length=64),
        ),
    ]
