# Generated by Django 4.1.1 on 2022-10-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0132_facturas_facturapagada'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonosoperacion',
            name='comprobanteCancelado',
            field=models.CharField(default='PENDIENTE', max_length=64),
        ),
    ]
