# Generated by Django 4.1.2 on 2022-10-24 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0134_facturas_stockact'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresos_stock',
            name='nuevo_stock',
            field=models.CharField(default='0', max_length=32),
        ),
        migrations.AddField(
            model_name='ingresos_stock',
            name='stock_anterior',
            field=models.CharField(default='0', max_length=32),
        ),
    ]
