# Generated by Django 4.1.2 on 2022-10-24 02:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0135_ingresos_stock_nuevo_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rolesUsuario',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=['1', '1', '1', '1'], size=None),
        ),
    ]
