# Generated by Django 4.1.2 on 2022-10-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0138_alter_boletas_productos_alter_boletas_servicios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresos_stock',
            name='referencia',
            field=models.CharField(default='Ingreso', max_length=64),
        ),
    ]
