# Generated by Django 4.1.2 on 2022-10-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0139_ingresos_stock_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='observacionFactura',
            field=models.CharField(default='', max_length=512),
        ),
    ]
