# Generated by Django 4.1.2 on 2022-10-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0141_alter_facturas_observacionfactura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='observacionFactura',
            field=models.CharField(default='Sin Observacion', max_length=512),
        ),
    ]
