# Generated by Django 4.1.2 on 2022-10-31 00:03

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0143_egreso_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventariosProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInventario', models.DateField(default=django.utils.timezone.now)),
                ('usuarioInventario', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), default=[], size=None)),
                ('estadoInventario', models.CharField(default='Revision', max_length=32)),
                ('ubicacionArchivo', models.FileField(upload_to='media/')),
            ],
        ),
    ]
