# Generated by Django 4.1.2 on 2022-10-31 00:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0145_inventariosproductos_codigoinventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariosproductos',
            name='codigoInventario',
            field=models.CharField(default='INV-0000', max_length=64),
        ),
        migrations.AlterField(
            model_name='inventariosproductos',
            name='estadoInventario',
            field=models.CharField(default='Revision', max_length=128),
        ),
        migrations.AlterField(
            model_name='inventariosproductos',
            name='usuarioInventario',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=[], size=None),
        ),
    ]
