# Generated by Django 4.1.2 on 2022-10-31 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0146_alter_inventariosproductos_codigoinventario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariosproductos',
            name='almacenInventario',
            field=models.CharField(default='Chimbote', max_length=64),
        ),
    ]
