# Generated by Django 4.1.3 on 2022-11-12 12:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0147_inventariosproductos_almaceninventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='config_docs',
            name='almacenesSistema',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=[], size=None),
        ),
    ]
