# Generated by Django 4.1.3 on 2022-11-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0148_config_docs_almacenessistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacredito',
            name='modoNota',
            field=models.CharField(default='DEVOLUCION_TOTAL', max_length=64),
        ),
    ]
