# Generated by Django 4.1.3 on 2022-11-26 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0150_alter_notacredito_fechaemision'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonosoperacion',
            name='fechaAbono',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
