# Generated by Django 4.1.3 on 2022-11-26 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0151_abonosoperacion_fechaabono'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciones',
            name='fecha_vencReg',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='cotizaciones',
            name='fecha_emision',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
