# Generated by Django 4.1.3 on 2022-11-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0152_cotizaciones_fecha_vencreg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciones',
            name='cred_dias',
            field=models.CharField(default='0', max_length=64),
        ),
    ]
