# Generated by Django 4.1.3 on 2022-11-27 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0153_cotizaciones_cred_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresos_stock',
            name='fecha_emision',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
