# Generated by Django 4.1.3 on 2022-11-27 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0154_ingresos_stock_fecha_emision'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciones',
            name='validez_dias',
            field=models.CharField(default='7', max_length=64),
        ),
        migrations.AddField(
            model_name='egreso_stock',
            name='fecha_emision',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
