# Generated by Django 4.1.3 on 2022-12-17 16:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0155_cotizaciones_validez_dias_egreso_stock_fecha_emision'),
    ]

    operations = [
        migrations.AddField(
            model_name='guias',
            name='origenGuia',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=512), default=[], size=None),
        ),
    ]
