# Generated by Django 4.1.3 on 2022-12-17 20:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0157_cotizaciones_mostrarcabos_cotizaciones_mostrarpanhos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciones',
            name='nombresColumnas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=64), default=[], size=None),
        ),
    ]
