# Generated by Django 4.1.3 on 2022-12-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0158_cotizaciones_nombrescolumnas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ubigeoDistrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distritoUbigeo', models.CharField(default='', max_length=256)),
                ('codigoUbigeo', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
