# Generated by Django 4.1.4 on 2023-01-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0159_ubigeodistrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonosoperacion',
            name='nro_operacion_2',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='abonosoperacion',
            name='nro_operacion',
            field=models.CharField(default='', max_length=64),
        ),
    ]
