# Generated by Django 4.1.4 on 2023-01-01 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0160_abonosoperacion_nro_operacion_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='comisiones_habilitado',
            field=models.CharField(default='1', max_length=8),
        ),
    ]
