# Generated by Django 4.1.4 on 2023-01-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0162_rename_comisiones_habilitado_clients_habilitado_comisiones'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='kpi_info',
            field=models.CharField(default='0', max_length=128),
        ),
    ]
