# Generated by Django 4.1.4 on 2023-01-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0163_products_kpi_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='max_endedudamiento',
            field=models.CharField(default='0', max_length=32),
        ),
        migrations.AddField(
            model_name='clients',
            name='tipo_cliente',
            field=models.CharField(default='S', max_length=8),
        ),
    ]
