# Generated by Django 4.1.4 on 2023-01-01 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0164_clients_max_endedudamiento_clients_tipo_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='max_endedudamiento',
            new_name='max_endeudamiento',
        ),
    ]
