# Generated by Django 4.1.4 on 2023-01-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0166_userprofile_descuento_maximo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariosproductos',
            name='inventario_descuento',
            field=models.CharField(default='0', max_length=64),
        ),
    ]
