# Generated by Django 4.1.4 on 2023-01-02 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0167_inventariosproductos_inventario_descuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventariosproductos',
            name='inventario_descuento',
        ),
    ]
