# Generated by Django 4.1.4 on 2023-01-02 01:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0168_remove_inventariosproductos_inventario_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='config_docs',
            name='almacenesDescuento',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=[], size=None),
        ),
    ]
