# Generated by Django 4.1.4 on 2023-01-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0169_config_docs_almacenesdescuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletas',
            name='stockAct',
            field=models.CharField(default='0', max_length=64),
        ),
    ]
