# Generated by Django 4.1.4 on 2023-01-09 20:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0170_boletas_stockact'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='producto_A',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=[], size=None),
        ),
        migrations.AddField(
            model_name='products',
            name='producto_B',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=[], size=None),
        ),
        migrations.AddField(
            model_name='products',
            name='producto_kit',
            field=models.CharField(default='0', max_length=12),
        ),
    ]
