# Generated by Django 4.1.5 on 2023-01-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0172_ordencompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='monedaOrden',
            field=models.CharField(default='SOLES', max_length=64),
        ),
    ]
