# Generated by Django 4.1.5 on 2023-01-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0173_alter_ordencompra_monedaorden'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonosoperacion',
            name='abono_comisionable',
            field=models.CharField(default='1', max_length=12),
        ),
    ]
