# Generated by Django 4.1.5 on 2023-01-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0175_boletas_codigoscotis'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletas',
            name='boletaPagada',
            field=models.CharField(default='0', max_length=64),
        ),
    ]
