# Generated by Django 4.1.5 on 2023-01-26 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0176_boletas_boletapagada'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacredito',
            name='estadoSunat',
            field=models.CharField(default='SinComprobar', max_length=32),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='stockAct',
            field=models.CharField(default='0', max_length=32),
        ),
    ]
