# Generated by Django 4.1.7 on 2023-03-20 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0180_ordencomprametalprotec'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencomprametalprotec',
            name='tcCompraOrden',
            field=models.CharField(default='0.000', max_length=8),
        ),
        migrations.AddField(
            model_name='ordencomprametalprotec',
            name='tcVentaOrden',
            field=models.CharField(default='0.000', max_length=8),
        ),
    ]
