# Generated by Django 4.1.7 on 2023-03-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0181_ordencomprametalprotec_tccompraorden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencomprametalprotec',
            name='mostrarDescuento',
            field=models.CharField(default='0', max_length=8),
        ),
    ]
