# Generated by Django 4.1.7 on 2023-03-30 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sistema_2', '0182_ordencomprametalprotec_mostrardescuento'),
    ]

    operations = [
        migrations.CreateModel(
            name='configComisiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentajeComision', models.CharField(default='0', max_length=8)),
                ('incluyeIgv', models.CharField(default='0', max_length=8)),
                ('usuarioRelacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
