# Generated by Django 4.1.7 on 2023-03-30 17:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sistema_2', '0183_configcomisiones'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='configComisiones',
            new_name='configurarComisiones',
        ),
    ]
