# Generated by Django 4.1.7 on 2023-04-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0186_configurarcomisiones_tipocomision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurarcomisiones',
            name='codigoComision',
            field=models.CharField(default='COM-0000', max_length=32),
        ),
    ]
