# Generated by Django 4.1.7 on 2023-04-13 06:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0187_configurarcomisiones_codigocomision'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoriaCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCategoria', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='departamentoCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDepartamento', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='divisionCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDivision', models.CharField(default='', max_length=64)),
                ('tipoCosto', models.CharField(default='', max_length=16)),
                ('comportamientoCosto', models.CharField(default='', max_length=16)),
                ('operativoCosto', models.CharField(default='', max_length=8)),
                ('categoriaAsociada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_2.categoriacosto')),
            ],
        ),
        migrations.CreateModel(
            name='registroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRegisto', models.DateField(default=datetime.date.today)),
                ('nroDocumento', models.CharField(default='', max_length=16)),
                ('rucRegistro', models.CharField(default='', max_length=16)),
                ('razonRegistro', models.CharField(default='', max_length=64)),
                ('conceptoRegistro', models.CharField(default='', max_length=64)),
                ('importeRegistro', models.CharField(default='', max_length=16)),
                ('monedaRegistro', models.CharField(default='', max_length=16)),
                ('divisionRelacionada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_2.divisioncosto')),
            ],
        ),
        migrations.AddField(
            model_name='categoriacosto',
            name='departamentoAsociado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_2.departamentocosto'),
        ),
    ]
