# Generated by Django 4.1.7 on 2023-04-13 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0188_categoriacosto_departamentocosto_divisioncosto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrocosto',
            old_name='conceptoRegistro',
            new_name='conceptoCosto',
        ),
        migrations.RenameField(
            model_name='registrocosto',
            old_name='importeRegistro',
            new_name='documentoCosto',
        ),
        migrations.RenameField(
            model_name='registrocosto',
            old_name='fechaRegisto',
            new_name='fechaCosto',
        ),
        migrations.RenameField(
            model_name='registrocosto',
            old_name='monedaRegistro',
            new_name='importeCosto',
        ),
        migrations.RenameField(
            model_name='registrocosto',
            old_name='nroDocumento',
            new_name='monedaCosto',
        ),
        migrations.RenameField(
            model_name='registrocosto',
            old_name='razonRegistro',
            new_name='razonCosto',
        ),
        migrations.RenameField(
            model_name='registrocosto',
            old_name='rucRegistro',
            new_name='rucCosto',
        ),
    ]
