# Generated by Django 4.1.7 on 2023-04-26 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0189_rename_conceptoregistro_registrocosto_conceptocosto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cajaChica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conceptoCaja', models.CharField(default='', max_length=32)),
                ('valorRegistrado', models.CharField(default='0', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ingresosCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorIngresado', models.CharField(default='0', max_length=32)),
                ('conceptoIngreso', models.CharField(default='', max_length=64)),
                ('cajaRelacionada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_2.cajachica')),
            ],
        ),
    ]
