# Generated by Django 4.1.7 on 2023-04-26 18:04

from django.db import migrations, models
import django.db.models.deletion
import sistema_2.models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0190_cajachica_ingresoscaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocosto',
            name='cajaRelacionada',
            field=models.ForeignKey(default=sistema_2.models.get_default_caja, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema_2.cajachica'),
        ),
    ]
