# Generated by Django 4.1.7 on 2023-04-27 03:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0192_cajachica_fechacreacion_cajachica_monedacaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresoscaja',
            name='fechaIngreso',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
