# Generated by Django 4.2.1 on 2023-05-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_2', '0194_config_docs_tipocambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencomprametalprotec',
            name='mostrarVU',
            field=models.CharField(default='0', max_length=8),
        ),
    ]
